### ISSUE TITLE
User Story: Refresh Data 

### ISSUE THREAD

**Issue by IGramajoO** [IGramajoO/Group5_CST438_Project01#1]
The user will want to refresh data so they can update old information. 

Regardless of what API we end up going with we could have a system to refresh info since data could be updated frequently. This could be lower priority and I don't think it'd be too hard

**Comment by rltsystems** [comment]
Great start! 
I think simplifying stories into this format will make them easier to tackle later:
“As a [persona], I [want to], [so that].”
i.e. As a user, I want to be able to have my data be updated (automatically or forced), so that I know that I'm looking at current (vs. outdated) data/info.

**Comment by rltsystems** [comment]
Reviewed and completed. If the user Swipes down from the RecyclerView for My Recipes, the recipes will populate the DB and show up on the recycler view (screen).
![image](https://user-images.githubusercontent.com/10646650/154427036-e8c5ca30-6b8d-4118-aa93-6e3042c4caa1.png)
