### ISSUE TITLE
User Story: Persistence 

### ISSUE THREAD

**Issue by IGramajoO** [IGramajoO/Group5_CST438_Project01#12]
As a user, I want my data to be persistent so I can access it across different sessions.

Basically a test to make sure the database works

**Comment by rltsystems** [comment]
Reviewed and Completed.

1.User Opens App
2. Create a user
3. Login with user
4. Go to My Recipes
**5. Tap on Add Recipes --> Swipe top down to refresh
6. Square button to minimize app
7. Re-open app, select My Recipes --> See that recipes are still there**
8. Tap on My Account
9. Update Password
10. Logout of Account
11. Login with new Password
