### ISSUE TITLE
User Story: View list of Saved Recipes

### ISSUE THREAD

**Issue by IGramajoO** [IGramajoO/Group5_CST438_Project01#3]
A user may want to see a list of the data 

The wording on this can be finalized when we choose what APIs we're gonna use, but regardless one of the requirements is using a recycler or list view.

**Comment by Edgy-Mcgee** [comment]
Now that we're decided on a recipe app, this is similar to the search function but different enough that I'm not gonna close it just yet.

**Comment by IGramajoO** [comment]
What i meant is for users to view their own list of recipes. I edited the title of the story to reflect that a bit better, sorry for the confusion

**Comment by rltsystems** [comment]
Reviewed and Completed.
