### ISSUE TITLE
User Story: Create an Account

### ISSUE THREAD

**Issue by rltsystems** [IGramajoO/Group5_CST438_Project01#5]
As a user, I want to be able to create an account, so that I can access my (personal data).

**Comment by Edgy-Mcgee** [comment]
This and #2 are the same

**Comment by IGramajoO** [comment]
Priority: 5
Difficulty: 2

**Comment by rltsystems** [comment]
Reviewed and Completed. 
![image](https://user-images.githubusercontent.com/10646650/154427186-1ad9222d-2512-42eb-835d-dd1e649e702f.png)
